version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "jam3snicholson/chucknorris-server"
    ports:
      - "9001:9000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "jam3snicholson/chucknorris-frontend"
    ports:
      - "3000:3000"
    links:
      - "server"